[package]
name = "hyperemu"
version = "0.1.4"
edition = "2024"
description = "A multi-architecture hardware emulator"

[features]
default = ["full"]

full = ["armv7", "x86", "rv32i", "elf", "gdb"]

elf = ["dep:goblin"]
gdb = ["dep:gdbstub", "dep:gdbstub_arch"]

armv7 = []
x86 = []
rv32i = []

[dependencies]
bitflags = "2.11"
thiserror = "2.0"
log = "0.4"
goblin = { version = "0.10", optional = true }
gdbstub = { version = "0.7", optional = true }
gdbstub_arch = { version = "0.3", optional = true }
